site_name: UAVcast-Pro
site_url: https://docs.uavmatrix.com/

# site_favicon: "images/favicon.ico"
extra:
  generator: false
  version:
    provider: mike
    default: "4.x"
  analytics:
    provider: google
    property: 'UA-59911815-6'
# extra_css:
#   - pages/style.css

nav:
  - Home: 
    - index.md
    - License: license/license.md
    - changelog.md
    - libraries.md
  - Getting started:
    - installation.md
    - How it works: how_it_works.md
    - What do i need: hardware.md
    
  
  - Setup:
    - 'pages/Cockpit.md'
    - 'pages/Dashboard.md'
    - 'pages/Flight-Controller.md'
    - 'pages/Ground-Control.md'
    - 'pages/Cell-Modem.md'
    - 'pages/Dynamic-DNS.md'
    - 'pages/Vpn.md'
    - 'pages/Application.md'
    - Camera:
        - 'pages/camera/Configuration.md'
        - 'pages/camera/HTTP Videostream.md'
    - Raspberry:
        - 'pages/raspberry/diagnostic.md'
        - 'pages/raspberry/network.md'
        - 'pages/raspberry/led.md'
    - application-update.md
  
  - Beta:
    - pages/beta.md
  - Developers:
      - developers/restapi.md
      - developers/translation.md
  - FAQ:
    - troubleshooting.md
  - UAVnet:
      - vpn/zerotier.md

theme:
  name: material
  custom_dir: overrides
  favicon: 'images/favicon.ico'
  language: 'en'
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/airplane
  features:
    # - navigation.instant
    # - navigation.tracking
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.tabs
    - navigation.expand
    # - navigation.indexes
    # - toc.integrate
    - navigation.top
    - announce.dismiss

repo_name: 'uavmatrix/uavcast-pro-docs'
repo_url: https://github.com/UAVmatrix/uavcast-pro-docs/
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed:
  #     alternate_style: true
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
# Copyright
copyright: 'Copyright &copy; 2018 - 2022 Bernt Christian Egeland'
